
        p1.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.3)
        p1.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)

        time.sleep(0.5)

        p1.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.23)
        p1.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)
        p1.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.23)
        p1.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)
        p1.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.23)

        #########

        p1.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)
        p3.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)

        time.sleep(0.5)

        p3.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)
        p3.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.23)
        p3.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)
        p3.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.23)
        p3.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)

        p4.ChangeDutyCycle(9)
        time.sleep(0.01)
