        p2.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.3)
        p2.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)

        time.sleep(0.5)

        p2.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.23)
        p2.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)
        p2.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.23)
        p2.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)
        p2.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.23)

        #########

        p2.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)
        p2.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)

        time.sleep(0.5)

        p2.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)
        p2.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.23)
        p2.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)
        p2.ChangeDutyCycle(5.5)
        p4.ChangeDutyCycle(5.5)
        time.sleep(0.23)
        p2.ChangeDutyCycle(9)
        p4.ChangeDutyCycle(9)
        time.sleep(0.23)

        
